package by.epam.naumovich.film_ordering.controller;

/**
 * An enumeration that contains all existing command names
 * 
 * @author Dmitry Naumovich
 * @version 1.0
 */
public enum CommandName {
	ADD_DISCOUNT,
	ADD_FILM,
	ADD_NEWS,
	ADD_ORDER,
	ADD_REVIEW,
	BAN_USER,
	CHANGE_LANGUAGE,
	CHANGE_USER_SETTINGS,
	DELETE_DISCOUNT,
	DELETE_FILM,
	DELETE_NEWS,
	DELETE_REVIEW,
	EDIT_DISCOUNT,
	EDIT_FILM,
	EDIT_NEWS,
	GET_NOVELTY,
	GET_SIDEBAR_NEWS,
	LOGIN, 
	LOGOUT,
	OPEN_ABOUT_US_PAGE,
	OPEN_ALL_FILMS,
	OPEN_ALL_NEWS, 
	OPEN_ALL_ORDERS,
	OPEN_ALL_REVIEWS,
	OPEN_ALL_USERS,
	OPEN_FEEDBACK_PAGE,	
	OPEN_FILM_EDIT_PAGE,
	OPEN_FILM_ORDERS,
	OPEN_HELP_PAGE,
	OPEN_LOGINATION_PAGE,
	OPEN_NEW_FILM_PAGE,
	OPEN_NEW_NEWS_PAGE,
	OPEN_NEW_ORDER_PAGE,
	OPEN_NEW_REVIEW_PAGE,
	OPEN_NEWS_EDIT_PAGE,
	OPEN_SIGN_UP_PAGE,
	OPEN_SINGLE_FILM, 
	OPEN_SINGLE_NEWS,
	OPEN_SINGLE_ORDER,
	OPEN_SINGLE_REVIEW,
	OPEN_USER_ORDERS,
	OPEN_USER_PROFILE,
	OPEN_USER_REVIEWS,
	OPEN_USER_SETTINGS,
	OPEN_WIDENED_SEARCH_PAGE,
	SIGN_UP,
	SEARCH_FILMS,
	SEARCH_FILMS_WIDENED,
	UNBAN_USER
}
