spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filmordering?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: dmitry
    password: 1234
    driver-class-name: org.gjt.mm.mysql.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp